apiVersion: batch/v1
kind: Job
metadata:
  name: container-runtime-probe
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: container-runtime-probe
          image: ghcr.io/bobiene/containerruntimeprobe:preview
          imagePullPolicy: Always
